version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    image: juandocki/backend:latest
    container_name: backend-app
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_DATABASE=adopcion_mascotas_db
      - DB_USERNAME=juanchi_dev
      - DB_PASSWORD=juanchi.POSTGRES.2025
    networks:
      - app-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: juandocki/frontend:latest
    container_name: frontend-app
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=adopcion_mascotas_db
      - POSTGRES_USER=juanchi_dev
      - POSTGRES_PASSWORD=juanchi.POSTGRES.2025
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
